### POST request to create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1995-09-19",
  "registeredDate": "2025-11-25"
}
###
